<?php

/**
 * Provide a admin area view for the plugin
 *
 * This file is used to markup the admin-facing aspects of the plugin.
 *
 * @link       http://example.com
 * @since      1.0.0
 *
 * @package    Plugin_Name
 * @subpackage Plugin_Name/admin/partials
 */

require ("wp-peon-header.php"); 
?>
<p>WP Peon is specifically design for back end developer so that they can easily modify or look WordPress files, You can say alternate WP Editor. Goal of plugins is to provide friendly access to most common WordPress action and filters.</p>
<h3>Custom HTML</h3>
<p>Add custom HTML in header, footer and blog posts.
</p>
<h3>Execute PHP</h3>
<p>Help to run PHP code in WordPress posts and pages using shortcodes generated by Execute PHP.
Usage 
Type in shortcode and type in PHP Code and then click save. To create new code just change the shortcode and add renew code below or refresh page to clear existing values.
</p>
<h3>WP Explorer</h3>
<p>An alternate WordPress Source Editor. With directory list view and open folder and nice breadcrumbs.</p>
<h3>Advance</h3>
<p>Modify .htaccess file or wp-config.php from Advance page. You can also enable debugging with given step and view debug.log directly on page.</p>